[project]
name = "poc-dbt-databricks"
version = "0.1.0"
description = "POC dbt project on Databricks"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "dbt-core>=1.10.15",
    "dbt-databricks>=1.11.0",
]
